spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

logging:
  level:
    com.memora: INFO
    org.hibernate.SQL: WARN

